### ISSUE TITLE
Publish project to explorer reports error, but it runs on local machine without any problem.

### ISSUE THREAD

**Issue by Cupnfish** [subquery/subql#1077]
Publish project to explorer reports error, but it runs on local machine without any problem.
```shell
2022-05-30 10:53:46        API/INIT: RPC methods not decorated: eth_feeHistory, eth_maxPriorityFeePerGas, moon_isBlockFinalized, moon_isTxFinalized
{"level":"error","timestamp":"2022-05-30T10:53:46.795Z","pid":7,"hostname":"subquery-14324-indexer-deployment-b455657d8-9rvvf","category":"ds-sandbox","message":"not supported ds @substrate/Moonbeam"}
{"level":"error","timestamp":"2022-05-30T10:53:46.796Z","pid":7,"hostname":"subquery-14324-indexer-deployment-b455657d8-9rvvf","category":"subql-node","payload":{"type":"error","name":"VMError","message":"Cannot find module './frontierEvm'","stack":"VMError: Cannot find module './frontierEvm'\n    at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:279:10)\n    at DefaultResolver.resolve (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:105:15)\n    at ReadOnlyHandler.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:479:11)\n    at requireImpl (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:84:28)\n    at require (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:165:10)\n    at /tmp/nOMiGJ/QmZRiERuKHcJVRHjH6UqbbWyfss3K3CC4nGPrtifPJzY1i.js:9:39\n    at BaseHandler.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:479:11)\n    at DsPluginSandbox.run (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:425:23)\n    at DefaultResolver.loadJS (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:203:7)\n    at loadJS (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:248:46)"},"message":"Node failed to start"}
```
Has anyone encountered a similar problem?

**Comment by Cupnfish** [comment]
https://github.com/pnsproject/pnsquery

**Comment by stwiname** [comment]
Hey @Cupnfish. Can you please try using the frontier evm processor and see if that fixes your issue. 

The Moonbeam obe is just an alias for the frontier one

**Comment by Cupnfish** [comment]
I tried to modify and submit a new commit: https://github.com/pnsproject/pnsquery/compare/main...try-fix-deploy

But a new error was reported：

```shell
2022-06-06 08:44:38        API/INIT: RPC methods not decorated: eth_feeHistory, eth_maxPriorityFeePerGas, moon_isBlockFinalized, moon_isTxFinalized
{"level":"error","timestamp":"2022-06-06T08:44:38.483Z","pid":7,"hostname":"subquery-14432-indexer-deployment-6b875b97dd-5q5ls","category":"ds-sandbox","payload":{"type":"error","name":"Error","message":"Cannot find module '@polkadot/api-augment'\nRequire stack:\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/ds-processor.service.js\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/indexer.module.js\n- /usr/local/lib/node_modules/@subql/node/dist/app.module.js\n- /usr/local/lib/node_modules/@subql/node/dist/main.js\n- /usr/local/lib/node_modules/@subql/node/bin/run","stack":"Error: Cannot find module '@polkadot/api-augment'\nRequire stack:\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/ds-processor.service.js\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/indexer.module.js\n- /usr/local/lib/node_modules/@subql/node/dist/app.module.js\n- /usr/local/lib/node_modules/@subql/node/dist/main.js\n- /usr/local/lib/node_modules/@subql/node/bin/run\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n    at Function.resolve (node:internal/modules/cjs/helpers:108:19)\n    at resolve (/usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js:54:36)\n    at DefaultResolver.newCustomResolver [as customResolver] (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver-compat.js:320:21)\n    at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:313:12)\n    at DefaultResolver.resolve (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:105:15)\n    at ReadOnlyHandler.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:479:11)\n    at requireImpl (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:84:28)\n    at require (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:165:10)\n    at /tmp/AkdgLd/QmNTxWGaNwXvPKi7KBGKHsGuMZb3pcVS66YZCh3knfNGk8.js:15:1"},"message":"not supported ds @substrate/FrontierEvm"}
{"level":"error","timestamp":"2022-06-06T08:44:38.484Z","pid":7,"hostname":"subquery-14432-indexer-deployment-6b875b97dd-5q5ls","category":"subql-node","payload":{"type":"error","name":"Error","message":"Cannot find module '@polkadot/api-augment'\nRequire stack:\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/ds-processor.service.js\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/indexer.module.js\n- /usr/local/lib/node_modules/@subql/node/dist/app.module.js\n- /usr/local/lib/node_modules/@subql/node/dist/main.js\n- /usr/local/lib/node_modules/@subql/node/bin/run","stack":"Error: Cannot find module '@polkadot/api-augment'\nRequire stack:\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/ds-processor.service.js\n- /usr/local/lib/node_modules/@subql/node/dist/indexer/indexer.module.js\n- /usr/local/lib/node_modules/@subql/node/dist/app.module.js\n- /usr/local/lib/node_modules/@subql/node/dist/main.js\n- /usr/local/lib/node_modules/@subql/node/bin/run\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n    at Function.resolve (node:internal/modules/cjs/helpers:108:19)\n    at resolve (/usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js:54:36)\n    at DefaultResolver.newCustomResolver [as customResolver] (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver-compat.js:320:21)\n    at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:313:12)\n    at DefaultResolver.resolve (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:105:15)\n    at ReadOnlyHandler.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:479:11)\n    at requireImpl (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:84:28)\n    at require (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:165:10)\n    at /tmp/AkdgLd/QmNTxWGaNwXvPKi7KBGKHsGuMZb3pcVS66YZCh3knfNGk8.js:15:1"},"message":"Node failed to start"}
Close
```

**Comment by stwiname** [comment]
Hey @Cupnfish 

I've made a PR on your repo https://github.com/pnsproject/pnsquery/pull/1 let me know if this fixes your problems. You will need the latest subql-node as well

**Comment by Cupnfish** [comment]
Thanks to @stwiname 's help, the deployment is now working!
