### ISSUE TITLE
Issue with ipfs publish for node-avalanche

### ISSUE THREAD

**Issue by lachlan1m** [subquery/subql#1163]
Context:

- Trying to index `https://github.com/HZHAIX/pangolin-approvals-tutorial.git` works locally but not on hosted service or network after using ipfs publish.

- Everything in the ipfs project.yaml is there (including filters). 

Relevant Errors when deploying to hosted service:

```
{"level":"error","timestamp":"2022-07-04T03:29:28.663Z","pid":7,"hostname":"subquery-14944-indexer-deployment-7b8747d5d8-smrnt","category":"fetch","payload":{"type":"error","name":"TypeError","message":"Cannot convert undefined to a BigInt","stack":"TypeError: Cannot convert undefined to a BigInt\n    at BigInt (<anonymous>)\n    at Object.t.handleLog (/tmp/cmnpen/QmV3XZMjMmedgYfnYjmXZzshzCGSSLocuzV1ncsYJpg7jd.js:1:53763)\n    at Object.<anonymous> (/tmp/cmnpen/sandbox:2:50)\n    at IndexerSandbox.run (/usr/local/lib/node_modules/@subql/node-avalanche/node_modules/@subql/x-vm2/lib/main.js:1202:29)\n    at IndexerSandbox.runTimeout (/usr/local/lib/node_modules/@subql/node-avalanche/dist/indexer/sandbox.service.js:59:44)\n    at IndexerSandbox.securedExec (/usr/local/lib/node_modules/@subql/node-avalanche/dist/indexer/sandbox.service.js:75:24)\n    at IndexerManager.indexBlockForRuntimeDs (/usr/local/lib/node_modules/@subql/node-avalanche/dist/indexer/indexer.manager.js:362:34)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async IndexerManager.indexBlockForDs (/usr/local/lib/node_modules/@subql/node-avalanche/dist/indexer/indexer.manager.js:71:9)\n    at async IndexerManager.indexBlock (/usr/local/lib/node_modules/@subql/node-avalanche/dist/indexer/indexer.manager.js:85:17)"},"message":"failed to index block at height 57374 handleLog([{\"address\":\"0xfa2c38470ad0a970240cf1afd35cd04d9e994e76\",\"topics\":[\"0xe2403640ba68fed3a2f88b7557551d1993f84b99bb10ff833f0cf8db0c5e0486\",\"0x000000000000000000000000d145f37c3a60514e64069878a06cc8bb1b6b96bf\"],\"data\":\"0x000000000000000000000000000000000000000000000243383754fd97ddefd6\",\"blockNumber\":57374,\"transactionHash\":\"0x5bb657e5acc78741cbf01afbfb0e158e2c6fd3696b08c06b7a60bc781df6b824\",\"transactionIndex\":0,\"blockHash\":\"0x095afd3fa95d7d7dff28ea4fb686d08086d73b308a9cd15940a8157d50da935b\",\"logIndex\":1,\"removed\":false}])"}
```

**Comment by jiqiang90** [comment]
ipfs deployment cid: QmUXVXXrNL5t7AanA2c7V5ygmF5sFkjZApdVj6JdGB8ZCD

**Comment by jiqiang90** [comment]
this deployment  `QmY2LfoNoBPyMg64TDKZ8UqV3x1asB1GicY4na31mnfHHh` is missing options and assets

**Comment by jiqiang90** [comment]
<img width="1022" alt="Screen Shot 2022-07-05 at 11 01 31 PM" src="https://user-images.githubusercontent.com/10431657/177434971-6274c3b7-0400-4023-86c4-25005d787235.png">

Error due to incorrect filter, this problem is fixed, should be closed now
