### ISSUE TITLE
ERROR failed to index block at height 14400 handleEventInfo(TypeError: Cannot read properties of undefined (reading 'block')

### ISSUE THREAD

**Issue by 99Kies** [subquery/subql#1279]
14400 block info:
![image](https://user-images.githubusercontent.com/45918704/188205310-26a291a6-153e-4430-b24e-3d877d47ff0f.png)

my code:
```typescript
export async function handleEventInfo(event: SubstrateEvent): Promise<void> {
    const record = new EventInfo(`${event.extrinsic.block.block.header.number}-${event.extrinsic.idx}-${event.idx}`);
    await makeSureExtrinsic(event.extrinsic);
    record.ExtrinsicHashId = event.extrinsic.extrinsic.hash.toString();
    record.EventID = event.idx;
    record.method = event.event.method;
    record.section = event.event.section;
    // record.meta = event.event.meta.toString();
    record.data = event.event.data.toString();
    // time
    const moment = event.extrinsic.block.block.extrinsics[0].args[0] as Compact<Moment>;
    record.timestamp = new Date(moment.toNumber());
    await record.save();
}
```

my log:
```
subquery-node_1   | 2022-09-02T17:09:41.257Z <BlockDispatcherService> ERROR failed to index block at height 14400 handleEventInfo(TypeError: Cannot read properties of undefined (reading 'block')
subquery-node_1   |     at Object.t.handleEventInfo (/app/dist/index.js:1:46104)
subquery-node_1   |     at /app/sandbox:2:50
subquery-node_1   |     at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
subquery-node_1   |     at IndexerSandbox.run (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:426:23)
subquery-node_1   |     at IndexerSandbox.runTimeout (/usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js:57:46)
subquery-node_1   |     at IndexerSandbox.securedExec (/usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js:73:24)
subquery-node_1   |     at IndexerManager.indexData (/usr/local/lib/node_modules/@subql/node/dist/indexer/indexer.manager.js:205:32)
subquery-node_1   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
subquery-node_1   |     at async IndexerManager.indexEvent (/usr/local/lib/node_modules/@subql/node/dist/indexer/indexer.manager.js:194:13)
subquery-node_1   |     at async IndexerManager.indexBlockData (/usr/local/lib/node_modules/@subql/node/dist/indexer/indexer.manager.js:164:13)) TypeError: Cannot read properties of undefined (reading 'block')
subquery-node_1   | 
subquery-node_1   | node:internal/process/promises:279
subquery-node_1   |             triggerUncaughtException(err, true /* fromPromise */);
subquery-node_1   |             ^
subquery-node_1   | TypeError [Error]: Cannot read properties of undefined (reading 'block')
subquery-node_1   |     at Object.t.handleEventInfo (/app/dist/index.js:1:46104)
subquery-node_1   |     at /app/sandbox:2:50
subquery-node_1   |     at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
subquery-node_1   |     at IndexerSandbox.run (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:426:23)
subquery-node_1   |     at IndexerSandbox.runTimeout (/usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js:57:46)
subquery-node_1   |     at IndexerSandbox.securedExec (/usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js:73:24)
subquery-node_1   |     at IndexerManager.indexData (/usr/local/lib/node_modules/@subql/node/dist/indexer/indexer.manager.js:205:32)
subquery-node_1   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
subquery-node_1   |     at async IndexerManager.indexEvent (/usr/local/lib/node_modules/@subql/node/dist/indexer/indexer.manager.js:194:13)
subquery-node_1   |     at async IndexerManager.indexBlockData (/usr/local/lib/node_modules/@subql/node/dist/indexer/indexer.manager.js:164:13) {
subquery-node_1   |   handler: 'handleEventInfo'
subquery-node_1   | }
```

**Comment by jiqiang90** [comment]
From the explorer screenshot I see this event might not be triggered from any extrinsic directly, thus `event.extrinsic` might get undefined.

To. resolve this issue 
```
 Cannot read properties of undefined (reading 'block')
```

we change to 


```
const moment = event.block.block.extrinsics[0].args[0] as Compact<Moment>;

```
