### ISSUE TITLE
Subquery Node not running in Docker

### ISSUE THREAD

**Issue by rizasoylu1993** [subquery/subql#1581]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

Hi I get an error when I stand up my subql project on docker. Subql-subquery-node is not working and I get the error in the log below. Can you please help?

2023-03-27 02:49:12     at Module._compile (node:internal/modules/cjs/loader:1155:14)
2023-03-27 02:49:12     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
2023-03-27 02:49:12     at Module.load (node:internal/modules/cjs/loader:1033:32)
2023-03-27 02:49:12     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
2023-03-27 02:49:12     at Module.require (node:internal/modules/cjs/loader:1057:19)
2023-03-27 02:49:12     at require (node:internal/modules/cjs/helpers:103:18)
2023-03-27 02:49:12     at Object.<anonymous> (/usr/local/lib/node_modules/@subql/node-avalanche/dist/init.js:9:22)
2023-03-27 02:50:14 /usr/local/lib/node_modules/@subql/node-avalanche/node_modules/@subql/node-core/dist/configure/NodeConfig.js:40
2023-03-27 02:50:14             throw new Error(`Load config from file ${filePath} is not exist`);
2023-03-27 02:50:14             ^
2023-03-27 02:50:14 
2023-03-27 02:50:14 Error: Load config from file ./app/project-local.yaml is not exist
2023-03-27 02:50:14     at Function.fromFile (/usr/local/lib/node_modules/@subql/node-avalanche/node_modules/@subql/node-core/dist/configure/NodeConfig.js:40:19)
2023-03-27 02:50:14     at Function.register (/usr/local/lib/node_modules/@subql/node-avalanche/dist/configure/configure.module.js:121:45)
2023-03-27 02:50:14     at Object.<anonymous> (/usr/local/lib/node_modules/@subql/node-avalanche/dist/app.module.js:26:48)
2023-03-27 02:50:14     at Module._compile (node:internal/modules/cjs/loader:1155:14)
2023-03-27 02:50:14     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
2023-03-27 02:50:14     at Module.load (node:internal/modules/cjs/loader:1033:32)
2023-03-27 02:50:14     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
2023-03-27 02:50:14     at Module.require (node:internal/modules/cjs/loader:1057:19)
2023-03-27 02:50:14     at require (node:internal/modules/cjs/helpers:103:18)
2023-03-27 02:50:14     at Object.<anonymous> (/usr/local/lib/node_modules/@subql/node-avalanche/dist/init.js:9:22)

### Details

My docker-compose.yml
`version: "3"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node:
    image: onfinality/subql-node-avalanche:latest
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=app
      - --disable-historical=true
      - --config=./app/project-local.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: onfinality/subql-query:latest
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
      "subquery-node":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000
`

**Comment by stwiname** [comment]
@rizasoylu1993 did you solve this issue? It looks like your `project-local.yaml` file doesn't exist. Its hard to know without having access to your project.

I'm going to close this issue, but feel free to reopen it if it is still an issue
