### ISSUE TITLE
Last processed block jump to future after restart

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1779]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [ ] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [ ] Are you reporting to the correct repository?
* [ ] Did you search for an existing issue or pull request?

### Description
My project stuck at 43351590 because an issue in the project code. I wasn't aware of that in the beginning, so I tried to add dictionary and replace endpoint, then suddenly my project can index passing this height.
Until later I found the code issue, it scare me out.

check the log attached below.

You can see for the first a few retries, the node always started from 43351590. But suddenly in another restart, it jumped to 43352542.

### Details

```
2023-05-31T03:34:05.755Z <subql-node> INFO Current @subql/node-ethereum version is 2.2.2 
2023-05-31T03:34:05.982Z <db> WARN Database does not support SSL connection, will try to connect without it 
2023-05-31T03:34:09.041Z <indexer> INFO indexer manager start 
2023-05-31T03:34:09.062Z <api.ethereum> INFO Api host: polygon-mainnet.g.alchemy.com, method: https 
2023-05-31T03:34:10.179Z <api.ethereum> INFO Chain doesnt support finalized tag 
2023-05-31T03:34:10.219Z <store> INFO Historical state is enabled 
2023-05-31T03:34:10.304Z <UnfinalizedBlocks> INFO Unfinalized blocks is disabled 
2023-05-31T03:34:13.264Z <dynamic-ds> INFO Loaded 0 dynamic datasources 
2023-05-31T03:34:16.014Z <subql-node> INFO Node started on port: 3000 
2023-05-31T03:34:37.259Z <dictionary> WARN failed to fetch dictionary result Error: query execution canceled due to statement timeout
2023-05-31T03:34:37.261Z <profiler> INFO DictionaryService, getDictionary, 21271.873800992966 ms 
2023-05-31T03:34:37.265Z <BlockDispatcherService> INFO Enqueueing blocks 43351590...43351689, total 100 blocks 
2023-05-31T03:34:37.267Z <BlockDispatcherService> INFO fetch block [43351590,43351689], total 100 blocks 
2023-05-31T03:34:38.738Z <profiler> INFO DictionaryService, getDictionary, 1439.735251069069 ms 
2023-05-31T03:34:38.756Z <api> ERROR Failed to fetch blocks 43351590...43351689 Error: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput
2023-05-31T03:34:39.035Z <api> ERROR Failed to fetch blocks 43351590...43351689 Error: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput
2023-05-31T03:34:39.052Z <FetchService> ERROR Having a problem when getting best block Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
2023-05-31T03:34:39.052Z <FetchService> ERROR Having a problem when getting finalized block Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
2023-05-31T03:34:39.724Z <api> ERROR Failed to fetch blocks 43351590...43351689 Error: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput
2023-05-31T03:34:40.079Z <api> ERROR Failed to fetch blocks 43351590...43351689 Error: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput
2023-05-31T03:34:40.090Z <profiler> INFO DictionaryService, getDictionary, 1304.884209036827 ms 
2023-05-31T03:34:40.090Z <FetchService> WARN Dictionary indexed block is behind current indexing block height 
2023-05-31T03:34:40.091Z <BlockDispatcherService> INFO Enqueueing blocks 43352542...43352641, total 100 blocks 
2023-05-31T03:34:40.091Z <BlockDispatcherService> INFO Enqueueing blocks 43352642...43352685, total 44 blocks 
2023-05-31T03:34:40.516Z <api> ERROR Failed to fetch blocks 43351590...43351689 Error: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput
2023-05-31T03:34:40.517Z <BlockDispatcherService> ERROR Failed to fetch blocks from queue Error: Maximum number of retries (5) reached.
2023-05-31T03:34:41.954Z <subql-node> INFO Current @subql/node-ethereum version is 2.2.2 
2023-05-31T03:34:42.188Z <db> WARN Database does not support SSL connection, will try to connect without it 
2023-05-31T03:34:45.252Z <indexer> INFO indexer manager start 
2023-05-31T03:34:45.277Z <api.ethereum> INFO Api host: polygon-mainnet.g.alchemy.com, method: https 
2023-05-31T03:34:46.244Z <api.ethereum> INFO Chain doesnt support finalized tag 
2023-05-31T03:34:46.279Z <store> INFO Historical state is enabled 
2023-05-31T03:34:46.380Z <UnfinalizedBlocks> INFO Unfinalized blocks is disabled 
2023-05-31T03:34:48.744Z <dynamic-ds> INFO Loaded 0 dynamic datasources 
2023-05-31T03:34:50.959Z <subql-node> INFO Node started on port: 3000 
2023-05-31T03:34:51.964Z <profiler> INFO DictionaryService, getDictionary, 1021.484876036644 ms 
2023-05-31T03:34:51.965Z <FetchService> WARN Dictionary indexed block is behind current indexing block height 
2023-05-31T03:34:51.972Z <BlockDispatcherService> INFO Enqueueing blocks 43352542...43352641, total 100 blocks 
2023-05-31T03:34:51.974Z <BlockDispatcherService> INFO fetch block [43352542,43352641], total 100 blocks 
2023-05-31T03:34:52.000Z <BlockDispatcherService> INFO Enqueueing blocks 43352642...43352694, total 53 blocks 
2023-05-31T03:34:52.762Z <api> ERROR Failed to fetch blocks 43352542...43352641 Error: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput
2023-05-31T03:34:53.035Z <api> ERROR Failed to fetch blocks 43352542...43352641 Error: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput
2023-05-31T03:34:53.813Z <api> ERROR Failed to fetch blocks 43352542...43352641 Error: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput
2023-05-31T03:34:54.086Z <api> ERROR Failed to fetch blocks 43352542...43352641 Error: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput
2023-05-31T03:34:54.361Z <api> ERROR Failed to fetch blocks 43352542...43352641 Error: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput
2023-05-31T03:34:54.361Z <BlockDispatcherService> ERROR Failed to fetch blocks from queue Error: Maximum number of retries (5) reached.
2023-05-31T03:34:55.818Z <subql-node> INFO Current @subql/node-ethereum version is 2.2.2 
2023-05-31T03:34:56.047Z <db> WARN Database does not support SSL connection, will try to connect without it 
2023-05-31T03:34:59.115Z <indexer> INFO indexer manager start 
2023-05-31T03:34:59.135Z <api.ethereum> INFO Api host: polygon.api.onfinality.io, method: https 
2023-05-31T03:35:00.670Z <api.ethereum> INFO Chain doesnt support finalized tag 
2023-05-31T03:35:00.709Z <store> INFO Historical state is enabled 
2023-05-31T03:35:00.780Z <UnfinalizedBlocks> INFO Unfinalized blocks is disabled 
2023-05-31T03:35:02.797Z <dynamic-ds> INFO Loaded 0 dynamic datasources 
2023-05-31T03:35:04.826Z <subql-node> INFO Node started on port: 3000 
2023-05-31T03:35:05.856Z <profiler> INFO DictionaryService, getDictionary, 1046.097333908081 ms 
2023-05-31T03:35:05.859Z <FetchService> WARN Dictionary indexed block is behind current indexing block height 
2023-05-31T03:35:05.871Z <BlockDispatcherService> INFO Enqueueing blocks 43352542...43352641, total 100 blocks 
2023-05-31T03:35:05.874Z <BlockDispatcherService> INFO fetch block [43352542,43352641], total 100 blocks 
2023-05-31T03:35:05.915Z <BlockDispatcherService> INFO Enqueueing blocks 43352642...43352700, total 59 blocks 
2023-05-31T03:35:12.219Z <BlockDispatcherService> INFO fetch block [43352642,43352700], total 59 blocks 
2023-05-31T03:35:16.400Z <BlockDispatcherService> INFO Enqueueing blocks 43352701...43352703, total 3 blocks 
2023-05-31T03:35:16.401Z <BlockDispatcherService> INFO fetch block [43352701,43352703], total 3 blocks 
2023-05-31T03:35:19.410Z <BlockDispatcherService> INFO Enqueueing blocks 43352704...43352706, total 3 blocks 
2023-05-31T03:35:19.410Z <BlockDispatcherService> INFO fetch block [43352704,43352706], total 3 blocks 
2023-05-31T03:35:24.422Z <BlockDispatcherService> INFO Enqueueing blocks 43352707...43352710, total 4 blocks 
2023-05-31T03:35:24.424Z <BlockDispatcherService> INFO fetch block [43352707,43352710], total 4 blocks 
2023-05-31T03:35:29.301Z <benchmark> INFO 5.22 blocks/s. Target height: 43,352,711. Current height: 43,352,710. Estimated time remaining: 0 days 00 hours 00 mins 
2023-05-31T03:35:29.520Z <BlockDispatcherService> INFO Enqueueing blocks 43352711...43352711, total 1 blocks 

```

**Indexer Version:** @subql/ethereum:v2.2.2
**Network Details:**
  * ploygon
  * polygon-dict-2

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by ianhe8x** [comment]
I suspect polygon dictionary, but 
```
2023-05-31T04:08:33.199Z <subql-node> INFO Current @subql/node-ethereum version is 2.2.2 
2023-05-31T04:08:33.412Z <db> WARN Database does not support SSL connection, will try to connect without it 
2023-05-31T04:08:36.489Z <indexer> INFO indexer manager start 
2023-05-31T04:08:36.508Z <api.ethereum> INFO Api host: polygon.api.onfinality.io, method: https 
2023-05-31T04:08:37.873Z <api.ethereum> INFO Chain doesnt support finalized tag 
2023-05-31T04:08:37.910Z <store> INFO Historical state is enabled 
2023-05-31T04:08:37.983Z <UnfinalizedBlocks> INFO Unfinalized blocks is disabled 
2023-05-31T04:08:39.979Z <dynamic-ds> INFO Loaded 0 dynamic datasources 
2023-05-31T04:08:42.335Z <subql-node> INFO Node started on port: 3000 
2023-05-31T04:08:49.273Z <profiler> INFO DictionaryService, getDictionary, 6950.6119619607925 ms 
2023-05-31T04:08:49.273Z <BlockDispatcherService> INFO Enqueueing blocks 43351590...43351590, total 1 blocks 
2023-05-31T04:08:49.275Z <BlockDispatcherService> INFO fetch block [43351590,43351590], total 1 blocks 
2023-05-31T04:08:50.543Z <sandbox> INFO handleExchangeOrderSent 
2023-05-31T04:08:51.131Z <BlockDispatcherService> ERROR failed to index block at height 43351590 handleExchangeOrderSent(Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="orders(uint256)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at u.makeError (webpack://subquery-network-exchange/node_modules/@ethersproject/logger/lib.esm/index.js:224:22)
    at u.throwError (webpack://subquery-network-exchange/node_modules/@ethersproject/logger/lib.esm/index.js:233:19)
    at Me.decodeFunctionResult (webpack://subquery-network-exchange/node_modules/@ethersproject/abi/lib.esm/interface.js:345:22)
    at rn.<anonymous> (webpack://subquery-network-exchange/node_modules/@ethersproject/contracts/lib.esm/index.js:293:47)
    at Generator.next (<anonymous>)
    at i (webpack://subquery-network-exchange/node_modules/@ethersproject/contracts/lib.esm/index.js:5:57)
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/vm2/lib/bridge.js:485:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)) Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="orders(uint256)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)


```

**Comment by ianhe8x** [comment]
Unless the polygon dictionary returns inconsistent results. But check this (a snippet from the first log)
```
2023-05-31T03:35:05.856Z <profiler> INFO DictionaryService, getDictionary, 1046.097333908081 ms 
2023-05-31T03:35:05.859Z <FetchService> WARN Dictionary indexed block is behind current indexing block height 
2023-05-31T03:35:05.871Z <BlockDispatcherService> INFO Enqueueing blocks 43352542...43352641, total 100 blocks 
```
Even it says dictionary was used, and successfully returned. the first batch of blocks are 100 blocks, which isn't like feed from dictionary.

**Comment by jiqiang90** [comment]
This was due to during indexing of block 43351590, dictionary start fetching next round start from height 43351591 - 43361590, and returned empty array. 

And this `jumpBufferedHeight` will interrupt , force update the latest processed height before 43351590 indexing complete.  

https://github.com/subquery/subql/blob/f457e8a7761819cb7fbd5044691a7c6c8c938996/packages/node-core/src/indexer/blockDispatcher/base-block-dispatcher.ts#L221
