### ISSUE TITLE
ERROR Flushing cache failed Error: Invalid value <BN: 24>

### ISSUE THREAD

**Issue by fewensa** [subquery/subql#1813]
### Prerequisites

* [x] Are you running the latest version(s)?
* [ ] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [ ] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

Failed to fetch Crab chain for block 698,769

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
   onfinality/subql-query:v2.0.0
**Indexer Version:** [What is the version of the indexer service?]
   onfinality/subql-node:v2.6.1
**Network Details:**
  * [Network] 
     Crab  wss://crab-rpc.darwiniacommunitydao.xyz
  * [Block height, a block height where the issue is happening]
     698,769
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. Fetch start from 698,760

**Example project:** [A link to a minimal example that can reproduce the issue]
https://github.com/darwinia-network/indexer/blob/upgrade-subql/subql/packages/bridger

cd subql
yarn install
yarn boot
yarn run build:common
yarn build:bridger -- crab
cd packages/bridger/
docker-compose up -d

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

```
docker logs -f --tail 10 node-subql-bridger-crab
2023-06-20T15:43:20.750Z <BlockDispatcherService> INFO fetch block [698779,698866], total 88 blocks
2023-06-20T15:43:21.086Z <BlockDispatcherService> INFO Enqueueing blocks 699063...699162, total 100 blocks
2023-06-20T15:43:26.168Z <BlockDispatcherService> INFO fetch block [698867,698950], total 84 blocks
2023-06-20T15:43:32.184Z <BlockDispatcherService> INFO fetch block [698951,699025], total 75 blocks
2023-06-20T15:43:32.630Z <BlockDispatcherService> INFO Enqueueing blocks 699163...699262, total 100 blocks
2023-06-20T15:43:33.042Z <connection-pool> INFO No suspended endpoints.
2023-06-20T15:43:35.092Z <benchmark> INFO 12.47 blocks/s. Target height: 701,036. Current height: 698,769. Estimated time remaining: 0 days 00 hours 03 mins
2023-06-20T15:43:37.815Z <StoreCache> ERROR Database transaction failed Error: Invalid value <BN: 24>
2023-06-20T15:43:38.177Z <BaseBlockDispatcherService> ERROR Flushing cache failed Error: Invalid value <BN: 24>
2023-06-20T15:43:59.041Z <subql-node> INFO Current @subql/node version is 2.6.1
2023-06-20T15:44:08.181Z <db> WARN Database does not support SSL connection, will try to connect without it
2023-06-20T15:44:11.915Z <indexer> INFO indexer manager start
2023-06-20T15:44:25.922Z <store> INFO Historical state is disabled
2023-06-20T15:44:29.375Z <UnfinalizedBlocks> INFO Unfinalized blocks is disabled
2023-06-20T15:44:30.831Z <dynamic-ds> INFO Loaded 0 dynamic datasources
2023-06-20T15:44:37.676Z <BlockDispatcherService> INFO Enqueueing blocks 698713...698812, total 100 blocks
2023-06-20T15:44:37.689Z <BlockDispatcherService> INFO fetch block [698713,698812], total 100 blocks
2023-06-20T15:44:37.712Z <BlockDispatcherService> INFO Enqueueing blocks 698813...698912, total 100 blocks
2023-06-20T15:44:37.718Z <BlockDispatcherService> INFO Enqueueing blocks 698913...699012, total 100 blocks
2023-06-20T15:44:37.727Z <BlockDispatcherService> INFO Enqueueing blocks 699013...699112, total 100 blocks
2023-06-20T15:44:37.764Z <subql-node> INFO Node started on port: 3000
2023-06-20T15:45:06.127Z <BlockDispatcherService> INFO fetch block [698813,698912], total 100 blocks
2023-06-20T15:45:06.244Z <sandbox> WARN Unable to find a source map for project
2023-06-20T15:45:06.244Z <sandbox> WARN Build your project with latest @subql/cli to generate a source map
2023-06-20T15:45:06.550Z <BlockDispatcherService> INFO Enqueueing blocks 699113...699212, total 100 blocks
2023-06-20T15:45:13.058Z <connection-pool> INFO No suspended endpoints.
2023-06-20T15:45:13.600Z <BlockDispatcherService> INFO fetch block [698913,699012], total 100 blocks
2023-06-20T15:45:13.607Z <BlockDispatcherService> INFO Enqueueing blocks 699213...699312, total 100 blocks
2023-06-20T15:45:17.791Z <StoreCache> ERROR Database transaction failed Error: Invalid value <BN: 24>
2023-06-20T15:45:18.070Z <BaseBlockDispatcherService> ERROR Flushing cache failed Error: Invalid value <BN: 24>
```

**Comment by fewensa** [comment]
The error is this field 
https://github.com/darwinia-network/indexer/blob/eaeaa8e6615058e6c5807fa710b04714e327368c/subql/packages/bridger/schema/bridge-s2s/schema.graphql#LL10C4-L10C20

I'm test start from block 698760, When scan https://crab.subscan.io/extrinsic/700084-2 event.

https://github.com/darwinia-network/indexer/blob/eaeaa8e6615058e6c5807fa710b04714e327368c/subql/packages/bridger/src/handler/logic/bridge-s2s/storage.ts#L45

the messageNonce is 48, and then receive 

```
bridger-subquery-node-1   | 2023-06-20T17:47:58.473Z <StoreCache> ERROR Database transaction failed Error: Invalid value <BN: 30>
bridger-subquery-node-1   | /usr/local/lib/node_modules/@subql/node/node_modules/@subql/x-sequelize/lib/sql-string.js:53
bridger-subquery-node-1   |     throw new Error(`Invalid value ${logger.inspect(val)}`);
bridger-subquery-node-1   |           ^
bridger-subquery-node-1   |
bridger-subquery-node-1   | Error: Invalid value <BN: 30>
bridger-subquery-node-1   |     at Object.escape (/usr/local/lib/node_modules/@subql/node/node_modules/@subql/x-sequelize/lib/sql-string.js:53:11)
bridger-subquery-node-1   |     at PostgresQueryGenerator.escape (/usr/local/lib/node_modules/@subql/node/node_modules/@subql/x-sequelize/lib/dialects/abstract/query-generator.js:763:22)
bridger-subquery-node-1   |     at /usr/local/lib/node_modules/@subql/node/node_modules/@subql/x-sequelize/lib/dialects/abstract/query-generator.js:259:21
bridger-subquery-node-1   |     at Array.map (<anonymous>)
bridger-subquery-node-1   |     at PostgresQueryGenerator.bulkInsertQuery (/usr/local/lib/node_modules/@subql/node/node_modules/@subql/x-sequelize/lib/dialects/abstract/query-generator.js:255:36)
bridger-subquery-node-1   |     at PostgresQueryInterface.bulkInsert (/usr/local/lib/node_modules/@subql/node/node_modules/@subql/x-sequelize/lib/dialects/abstract/query-interface.js:346:68)
bridger-subquery-node-1   |     at recursiveBulkCreate (/usr/local/lib/node_modules/@subql/node/node_modules/@subql/x-sequelize/lib/model.js:1697:52)
bridger-subquery-node-1   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
bridger-subquery-node-1   |     at async NeedRelayBlock.bulkCreate (/usr/local/lib/node_modules/@subql/node/node_modules/@subql/x-sequelize/lib/model.js:1786:12)
bridger-subquery-node-1   |     at async Promise.all (index 1)
bridger-subquery-node-1   |
```


0x30 is 48.  I'm not sure what's happen when store this value.

**Comment by stwiname** [comment]
Hi @fewensa 

The type is wrong here https://github.com/darwinia-network/indexer/blob/eaeaa8e6615058e6c5807fa710b04714e327368c/subql/packages/bridger/src/handler/logic/bridge-s2s/storage.ts#L45, its a `U64` type so it needs to be converted to a number

This diff should fix it.

Also i think https://github.com/darwinia-network/indexer/blob/eaeaa8e6615058e6c5807fa710b04714e327368c/subql/packages/bridger/src/handler/logic/bridge-s2s/storage.ts#L54 will need to be updated too


```diff
diff --git a/subql/packages/bridger/src/handler/logic/bridge-s2s/storage.ts b/subql/packages/bridger/src/handler/logic/bridge-s2s/storage.ts
index e23dcec..bf0e845 100644
--- a/subql/packages/bridger/src/handler/logic/bridge-s2s/storage.ts
+++ b/subql/packages/bridger/src/handler/logic/bridge-s2s/storage.ts
@@ -5,7 +5,7 @@ import {FastBlock, FastEvent} from "@darwinia/index-common";
 import {BridgeS2SOnDemandType, BridgeS2SRelayBlockOrigin, BridgeS2SRelayBlockType} from "./types";
 // @ts-ignore
 import {JustificationMapping, NeedRelayBlock} from "../../../types";
-import {Justifications} from "@polkadot/types/interfaces/runtime/types";
+import {Justifications, FixedU64} from "@polkadot/types/interfaces/runtime/types";

 export class NeedRelayBlockStorage {
   private readonly event: FastEvent;
@@ -42,9 +42,9 @@ export class NeedRelayBlockStorage {

     if (_event.type == BridgeS2SRelayBlockType.OnDemand && this.onDemandType == BridgeS2SOnDemandType.SendMessage) {
       const data = this.event.data;
-      const [laneId, messageNonce] = data as unknown as [string, number];
+      const [laneId, messageNonce] = data as unknown as [string, FixedU64];
       _event.laneId = laneId.toString().replace('0x', '');
-      _event.messageNonce = messageNonce;
+      _event.messageNonce = messageNonce.toNumber();
     }
     if (_event.type == BridgeS2SRelayBlockType.OnDemand && this.onDemandType == BridgeS2SOnDemandType.Dispatch) {
       const data = this.event.data;
```

**Comment by fewensa** [comment]
It works, Thanks!
