### ISSUE TITLE
error: unsupported startup parameter: statement_timeout

### ISSUE THREAD

**Issue by pamanseau** [subquery/subql#2573]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

```log
024-10-19T17:05:24.152Z <subql-query> INFO Current @subql/query version is 2.15.2 
2024-10-19T17:05:24.168Z <nestjs> INFO Starting Nest application... 
2024-10-19T17:05:24.199Z <nestjs> INFO AppModule dependencies initialized 
2024-10-19T17:05:24.199Z <nestjs> INFO ConfigureModule dependencies initialized 
2024-10-19T17:05:24.199Z <nestjs> INFO GraphqlModule dependencies initialized 
2024-10-19T17:05:24.201Z <subql-query> INFO Started playground at http://localhost:3000 
/node_modules/pg-pool/index.js:45
    Error.captureStackTrace(err)
          ^

error: unsupported startup parameter: statement_timeout
    at /node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getDbType (/node_modules/@subql/common/dist/project/database/databaseUtil.js:8:20)
    at async GraphqlModule.onModuleInit (/dist/graphql/graphql.module.js:73:24)
    at async callModuleInitHook (/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at async NestApplication.callInitHook (/node_modules/@nestjs/core/nest-application-context.js:224:13)
    at async NestApplication.init (/node_modules/@nestjs/core/nest-application.js:98:9)
    at async NestApplication.listen (/node_modules/@nestjs/core/nest-application.js:168:33)
    at async /dist/main.js:34:5 {
  length: 69,
  severity: 'FATAL',
  code: '08P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  ```
### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql-query`.]
**Query Version:** v.2.15.2
**Indexer Version:** v.5.2.6
**Network Details:**
  * Polkadot

### Steps to Reproduce

1. Run in Kubernetes
2. Postgres 16 cluster with PGBounce

```yaml
DB_DATABASE : comai
DB_HOST : graph.postgres
DB_PASS : XXXX-XXXX-XXXX-XXXX
DB_PORT : 5432
DB_USER : postgres
GRAPHILE_ENV : production
```
**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** Connection to Postgres 16

**Actual behavior:** 

### Any other information

Related Issue: https://github.com/brianc/node-postgres/issues/2103

**Comment by stwiname** [comment]
Setting ` --query-timeout=0` should fix this.

**Comment by pamanseau** [comment]
@stwiname Yes it did solve the issue. Should you document it?
