### ISSUE TITLE
Node v16 not supported

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#356]
I could not run `npm i` on node v16.0.0 (npm v7.10.0)

I had to downgrade to node v14.17.1 and npm v6.14.13

**Comment by jamesbayly** [comment]
```6665 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
6665 verbose stack     at unsupportedURLType (/Users/james/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:203:15)
6665 verbose stack     at fromURL (/Users/james/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:261:13)
6665 verbose stack     at Function.resolve (/Users/james/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:80:12)
6665 verbose stack     at Arborist.[nodeFromEdge] (/Users/james/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:944:22)
6665 verbose stack     at Arborist.[buildDepStep] (/Users/james/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:891:36)
6665 verbose stack     at async Arborist.buildIdealTree (/Users/james/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:217:7)
6665 verbose stack     at async Promise.all (index 1)
6665 verbose stack     at async Arborist.reify (/Users/james/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
6665 verbose stack     at async Install.install (/Users/james/.nvm/versions/node/v16.0.0/lib/node_modules/npm/lib/install.js:137:5)
6666 verbose cwd /Users/james/Development/OnFinality/subql
6667 verbose Darwin 20.5.0
6668 verbose argv "/Users/james/.nvm/versions/node/v16.0.0/bin/node" "/Users/james/.nvm/versions/node/v16.0.0/bin/npm" "i" "vuepress"
6669 verbose node v16.0.0
6670 verbose npm  v7.10.0
6671 error code EUNSUPPORTEDPROTOCOL
6672 error Unsupported URL Type "workspace:": workspace:*
6673 verbose exit 1```

**Comment by ianhe8x** [comment]
We stick to lts version, which is v14. Will revisit this issue after 2021-10-26 when v16 become active lts.
