### ISSUE TITLE
Error: Unable to create Enum via index 13, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12

### ISSUE THREAD

**Issue by ashi20192020** [subquery/subql#423]
I am following Kitty example https://github.com/subquery/subql-examples/tree/main/kitty to setup subql for my project but I am getting below error while running `yarn generate:meta`

```
Generating from metadata, 119,779 bytes


/Users/ayush/workspace/parallel-subql/node_modules/@polkadot/util/assert.cjs:34
    throw new Error((0, _function.isFunction)(message) ? message() : message);
          ^
Error: Unable to create Enum via index 13, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12
    at assert (/Users/ayush/workspace/parallel-subql/node_modules/@polkadot/util/assert.cjs:34:11)
    at createFromValue (/Users/ayush/workspace/parallel-subql/node_modules/@polkadot/types/codec/Enum.cjs:87:20)
    at decodeFromValue (/Users/ayush/workspace/parallel-subql/node_modules/@polkadot/types/codec/Enum.cjs:118:14)
    at decodeEnum (/Users/ayush/workspace/parallel-subql/node_modules/@polkadot/types/codec/Enum.cjs:142:10)
    at new Enum (/Users/ayush/workspace/parallel-subql/node_modules/@polkadot/types/codec/Enum.cjs:196:21)
    at new <anonymous> (/Users/ayush/workspace/parallel-subql/node_modules/@polkadot/types/codec/Enum.cjs:211:9)
    at new Type (/Users/ayush/workspace/parallel-subql/node_modules/@polkadot/types/create/registry.cjs:349:16)
    at decodeU8a (/Users/ayush/workspace/parallel-subql/node_modules/@polkadot/types/codec/utils/decodeU8a.cjs:24:19)
    at decodeStruct (/Users/ayush/workspace/parallel-subql/node_modules/@polkadot/types/codec/Struct.cjs:98:41)
    at new Struct (/Users/ayush/workspace/parallel-subql/node_modules/@polkadot/types/codec/Struct.cjs:132:26)
error Command failed with exit code 1.
```

Here is source code https://github.com/parallel-finance/parallel-subql/tree/set-up-subql. Please check and let me know if I am missing anything.

**Comment by ianhe8x** [comment]
Seems this is an issue of polkadot/typegen, the better place is to raise it is in polkadot/api's repo. 
Also do note that typegen isn't required to use subql, it is only for improving typescript hints in IDE.

**Comment by jiqiang90** [comment]
I believe it is due to polkadot packages version too low, i have open a ticket to polkadot to fix the previous issue (https://github.com/polkadot-js/api/issues/3860).  And after fix we can try again.
