### ISSUE TITLE
Unhealthy service when deploying

### ISSUE THREAD

**Issue by lamafab** [subquery/subql#843]
Hello, I'm having some issues that are hard to debug. SubQuery Projects keeps failing to deploy my code, for both the staging and production slot. Locally I can build it just fine (`yarn codegen && yarn build`). I haven't setup the database locally yet, but based on the output of `subql-node`, the project layout is probably fine:

```bash
vscode ➜ /workspaces/subquery-polkadot-governance (main ✗) $ subql-node -f .
2022-03-08T17:14:46.628Z <db> ERROR Unable to connect to the database SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
2022-03-08T17:14:49.631Z <db> ERROR Unable to connect to the database SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
2022-03-08T17:14:52.633Z <db> ERROR Unable to connect to the database SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
```

My project:

* https://project.subquery.network/project/lamafab/polkadot-governance
* https://github.com/lamafab/subquery-polkadot-governance

### Staging Slot log:

> Create Subquery project from given path failed! Error: Entry file undefined for datasource not exist at loadDataSourceScript (/usr/local/lib/node_modules/@subql/node/dist/utils/project.js:163:15) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async /usr/local/lib/node_modules/@subql/node/dist/utils/project.js:73:29 at async Promise.all (index 0) at async loadProjectFromManifest0_2_0 (/usr/local/lib/node_modules/@subql/node/dist/configure/SubqueryProject.js:65:25) at async InstanceWrapper.project [as metatype] (/usr/local/lib/node_modules/@subql/node/dist/configure/configure.module.js:109:23) at async Injector.instantiateClass (/usr/local/lib/node_modules/@subql/node/node_modules/@nestjs/core/injector/injector.js:305:37) at async callback (/usr/local/lib/node_modules/@subql/node/node_modules/@nestjs/core/injector/injector.js:48:30) at async Injector.resolveConstructorParams (/usr/local/lib/node_modules/@subql/node/node_modules/@nestjs/core/injector/injector.js:124:24) at async Injector.loadInstance (/usr/local/lib/node_modules/@subql/node/node_modules/@nestjs/core/injector/injector.js:52:9)

### Production Slot log:

> No data

**Comment by lamafab** [comment]
So, I setup everything locally and it works. Still no luck with your hosted solution.

```bash
vscode ➜ /workspace (main ✗) $ subql-node -f .
2022-03-08T18:43:04.563Z <subql-node> INFO Node started on port: 3000 
2022-03-08T18:43:05.871Z <fetch> INFO fetch block [9342824,9342825], total 2 blocks 
2022-03-08T18:43:10.137Z <fetch> INFO fetch block [9342826,9342826], total 1 blocks 
2022-03-08T18:43:15.355Z <fetch> INFO fetch block [9342827,9342827], total 1 blocks 
2022-03-08T18:43:20.614Z <fetch> INFO fetch block [9342828,9342828], total 1 blocks 
2022-03-08T18:43:31.367Z <fetch> INFO fetch block [9342829,9342830], total 2 blocks 
2022-03-08T18:43:34.240Z <benchmark> INFO 0.19 bps, target: #9342830, current: #9342830, estimate time: 0 days 00 hours 00 mins 
2022-03-08T18:43:40.585Z <fetch> INFO fetch block [9342831,9342831], total 1 blocks 
2022-03-08T18:43:45.840Z <fetch> INFO fetch block [9342832,9342832], total 1 blocks 
2022-03-08T18:43:49.239Z <benchmark> INFO 0.14 bps, target: #9342832, current: #9342832, estimate time: 0 days 00 hours 00 mins 
2022-03-08T18:43:56.222Z <fetch> INFO fetch block [9342833,9342834], total 2 blocks 
```

**Comment by zhex** [comment]
from the error log on the hosted service, I will say the issue is caused by the failure in the build step. So I suggest removing your node_module and reinstalling all the dependencies on your local and trying to run the `yarn build` again, you might find something failed.

Also, we are currently improving the hosted service to allow users to view more information on why the service is failed in deployment.

**Comment by lamafab** [comment]
Okay, so the "View error log" (is this new?) gave me more info now:

```
===============================
---------Subql Codegen---------
===============================
Loading substrate manifest...
* Schema Proposed generated !
* Schema Tabled generated !
* Schema ExternalTabled generated !
* Schema Started generated !
* Schema Passed generated !
* Schema NotPassed generated !
* Schema Cancelled generated !
* Schema Executed generated !
* Schema ExecutedError generated !
* Schema ModuleError generated !
* Schema Delegated generated !
* Schema Undelegated generated !
* Schema Vetoed generated !
* Schema PreimageNoted generated !
* Schema PreimageUsed generated !
* Schema PreimageInvalid generated !
* Schema PreimageMissing generated !
* Schema PreimageReaped generated !
* Schema Blacklisted generated !
* Schema Voted generated !
* Schema VoteStandard generated !
* Schema Vote generated !
* Schema VoteSplit generated !
* Schema Seconded generated !
* Models index generated !
* Types index generated !
Done in 2.47s.
yarn run v1.22.17
$ tsc -b
src/types/models/index.ts(21,29): error TS2307: Cannot find module './executedError' or its corresponding type declarations.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
build code failed
```

The issue was with the generated types when running `yarn codegen`. I kind of assumed the hosted service would not run that command, but rather must be done manually by me (should the generated types not be tracked by git?). Anyway, it's fixed now, service is "RUNNING".
